quarkus.http.port=8080

quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=${DB_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl}
quarkus.datasource.username=${DB_USERNAME:}
quarkus.datasource.password=${DB_PASSWORD:}

quarkus.jackson.serialization-inclusion=non-null
