CREATE TABLE AGENDA_CONSULTA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VOLUNTARIO_ID NUMBER NOT NULL,
    PACIENTE VARCHAR2(255) NOT NULL,
    TIPO VARCHAR2(100) NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    HORARIO VARCHAR2(10) NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    TIPO_PESSOA VARCHAR2(50)
);

CREATE INDEX IDX_AGENDA_VOL ON AGENDA_CONSULTA(VOLUNTARIO_ID);
CREATE INDEX IDX_AGENDA_DATA ON AGENDA_CONSULTA(DATA_CONSULTA);
