ALTER TABLE pessoa_atendida ADD ID_CONTA NUMBER;

ALTER TABLE pessoa_atendida ADD CONSTRAINT FK_PESSOA_ATENDIDA_CONTA
FOREIGN KEY (ID_CONTA) REFERENCES T_CONTA_USUARIO(ID_CONTA);

ALTER TABLE pessoa_atendida ADD CONSTRAINT UK_PESSOA_ATENDIDA_CONTA UNIQUE (ID_CONTA);

ALTER TABLE ATENDIMENTO ADD DESCRICAO VARCHAR2(1000);
