CREATE TABLE T_MENSAGEM_CONTATO (
    ID_MENSAGEM_CONTATO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    MENSAGEM VARCHAR2(4000) NOT NULL,
    DATA_ENVIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLASSIFICACAO_IA VARCHAR2(50),
    LIDA NUMBER(1) DEFAULT 0 NOT NULL
);
