CREATE TABLE PRONTUARIO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VOLUNTARIO_ID NUMBER NOT NULL,
    AGENDA_ID NUMBER NOT NULL,
    PACIENTE VARCHAR2(255) NOT NULL,
    HISTORICO_MEDICO VARCHAR2(1000),
    TRATAMENTO_ATUAL VARCHAR2(2000),
    DATA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_PRONTUARIO_VOL ON PRONTUARIO(VOLUNTARIO_ID);
CREATE INDEX IDX_PRONTUARIO_AGE ON PRONTUARIO(AGENDA_ID);
