ALTER TABLE VOLUNTARIO ADD (
    STATUS_APROVACAO VARCHAR2(30) DEFAULT 'PENDENTE' NOT NULL,
    MOTIVO_VOLUNTARIADO VARCHAR2(1000)
);

ALTER TABLE VOLUNTARIO ADD CONSTRAINT CK_VOLUNTARIO_STATUS_APROVACAO
CHECK (STATUS_APROVACAO IN ('PENDENTE', 'APROVADO', 'RECUSADO'));
