ALTER TABLE VOLUNTARIO ADD CODIGO_INDICACAO VARCHAR2(50) UNIQUE;
ALTER TABLE VOLUNTARIO ADD PONTOS_INDICACAO NUMBER(10) DEFAULT 0 NOT NULL;
ALTER TABLE VOLUNTARIO ADD ID_VOLUNTARIO_INDICADOR NUMBER(10);

ALTER TABLE VOLUNTARIO ADD CONSTRAINT FK_VOLUNTARIO_INDICADOR 
FOREIGN KEY (ID_VOLUNTARIO_INDICADOR) REFERENCES VOLUNTARIO(ID);
