-- ============================================================
-- TDB Responde - Sprint 4 - Oracle SQL
-- 03_insert_data.sql
--
-- Dados demonstrativos coerentes com o projeto.
-- Cada tabela exigida possui pelo menos 7 linhas inseridas.
-- Execute depois de 02_create_tables.sql.
-- ============================================================

-- 15 contas: 7 voluntarios, 7 beneficiarios e 1 admin.
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (1, 'Ana Souza', 'ana.souza@example.com', 'hash_demo_001', 'VOLUNTARIO', 1, TIMESTAMP '2026-05-01 08:00:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (2, 'Carlos Lima', 'carlos.lima@example.com', 'hash_demo_002', 'VOLUNTARIO', 1, TIMESTAMP '2026-05-01 08:05:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (3, 'Beatriz Nunes', 'beatriz.nunes@example.com', 'hash_demo_003', 'VOLUNTARIO', 1, TIMESTAMP '2026-05-01 08:10:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (4, 'Joao Pereira', 'joao.pereira@example.com', 'hash_demo_004', 'VOLUNTARIO', 1, TIMESTAMP '2026-05-01 08:15:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (5, 'Marina Costa', 'marina.costa@example.com', 'hash_demo_005', 'VOLUNTARIO', 1, TIMESTAMP '2026-05-01 08:20:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (6, 'Rafael Dias', 'rafael.dias@example.com', 'hash_demo_006', 'VOLUNTARIO', 1, TIMESTAMP '2026-05-01 08:25:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (7, 'Laura Mendes', 'laura.mendes@example.com', 'hash_demo_007', 'VOLUNTARIO', 0, TIMESTAMP '2026-05-01 08:30:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (8, 'Responsavel Sol', 'responsavel.sol@example.com', 'hash_demo_008', 'BENEFICIARIO', 1, TIMESTAMP '2026-05-02 09:00:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (9, 'Responsavel Lua', 'responsavel.lua@example.com', 'hash_demo_009', 'BENEFICIARIO', 1, TIMESTAMP '2026-05-02 09:10:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (10, 'Responsavel Rio', 'responsavel.rio@example.com', 'hash_demo_010', 'BENEFICIARIO', 1, TIMESTAMP '2026-05-02 09:20:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (11, 'Responsavel Flor', 'responsavel.flor@example.com', 'hash_demo_011', 'BENEFICIARIO', 1, TIMESTAMP '2026-05-02 09:30:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (12, 'Responsavel Mar', 'responsavel.mar@example.com', 'hash_demo_012', 'BENEFICIARIO', 1, TIMESTAMP '2026-05-02 09:40:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (13, 'Responsavel Vida', 'responsavel.vida@example.com', 'hash_demo_013', 'BENEFICIARIO', 1, TIMESTAMP '2026-05-02 09:50:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (14, 'Responsavel Aurora', 'responsavel.aurora@example.com', 'hash_demo_014', 'BENEFICIARIO', 1, TIMESTAMP '2026-05-02 10:00:00');
INSERT INTO T_CONTA_USUARIO (ID_CONTA, NOME, EMAIL, SENHA_HASH, TIPO_USUARIO, ATIVO, DATA_CRIACAO)
VALUES (15, 'Administrador TDB', 'admin.tdb@example.com', 'hash_demo_015', 'ADMIN', 1, TIMESTAMP '2026-05-02 10:10:00');

-- 7 canais.
INSERT INTO CANAL_COMUNICACAO (ID, NOME, DESCRICAO) VALUES (1, 'WhatsApp', 'Contato por mensagem instantanea.');
INSERT INTO CANAL_COMUNICACAO (ID, NOME, DESCRICAO) VALUES (2, 'Telefone', 'Ligacao realizada pela equipe.');
INSERT INTO CANAL_COMUNICACAO (ID, NOME, DESCRICAO) VALUES (3, 'Email', 'Contato por correio eletronico.');
INSERT INTO CANAL_COMUNICACAO (ID, NOME, DESCRICAO) VALUES (4, 'Presencial', 'Atendimento presencial em unidade parceira.');
INSERT INTO CANAL_COMUNICACAO (ID, NOME, DESCRICAO) VALUES (5, 'Formulario Web', 'Solicitacao feita pelo site.');
INSERT INTO CANAL_COMUNICACAO (ID, NOME, DESCRICAO) VALUES (6, 'Escola Parceira', 'Encaminhamento por escola parceira.');
INSERT INTO CANAL_COMUNICACAO (ID, NOME, DESCRICAO) VALUES (7, 'ONG Parceira', 'Encaminhamento por organizacao parceira.');

-- 7 especialidades.
INSERT INTO ESPECIALIDADE (ID, NOME, DESCRICAO) VALUES (1, 'Odontologia', 'Avaliacao e orientacao odontologica.');
INSERT INTO ESPECIALIDADE (ID, NOME, DESCRICAO) VALUES (2, 'Psicologia', 'Acolhimento e escuta psicologica.');
INSERT INTO ESPECIALIDADE (ID, NOME, DESCRICAO) VALUES (3, 'Assistencia Social', 'Orientacao social e encaminhamento.');
INSERT INTO ESPECIALIDADE (ID, NOME, DESCRICAO) VALUES (4, 'Juridico', 'Orientacao juridica inicial.');
INSERT INTO ESPECIALIDADE (ID, NOME, DESCRICAO) VALUES (5, 'Triagem', 'Classificacao de prioridade e direcionamento.');
INSERT INTO ESPECIALIDADE (ID, NOME, DESCRICAO) VALUES (6, 'Pedagogia', 'Apoio a casos encaminhados por escolas.');
INSERT INTO ESPECIALIDADE (ID, NOME, DESCRICAO) VALUES (7, 'Enfermagem', 'Orientacao basica de saude.');

-- 7 voluntarios.
INSERT INTO VOLUNTARIO (ID, NOME, USUARIO, SENHA, ACESSO_SIGILO, DISPONIVEL, ID_CONTA, STATUS_APROVACAO, MOTIVO_VOLUNTARIADO)
VALUES (1, 'Ana Souza', 'ana.souza', 'hash_demo_001', 1, 1, 1, 'APROVADO', 'Atuar em orientacao odontologica.');
INSERT INTO VOLUNTARIO (ID, NOME, USUARIO, SENHA, ACESSO_SIGILO, DISPONIVEL, ID_CONTA, STATUS_APROVACAO, MOTIVO_VOLUNTARIADO)
VALUES (2, 'Carlos Lima', 'carlos.lima', 'hash_demo_002', 0, 1, 2, 'APROVADO', 'Apoiar triagem social.');
INSERT INTO VOLUNTARIO (ID, NOME, USUARIO, SENHA, ACESSO_SIGILO, DISPONIVEL, ID_CONTA, STATUS_APROVACAO, MOTIVO_VOLUNTARIADO)
VALUES (3, 'Beatriz Nunes', 'beatriz.nunes', 'hash_demo_003', 1, 0, 3, 'APROVADO', 'Acolhimento psicologico.');
INSERT INTO VOLUNTARIO (ID, NOME, USUARIO, SENHA, ACESSO_SIGILO, DISPONIVEL, ID_CONTA, STATUS_APROVACAO, MOTIVO_VOLUNTARIADO)
VALUES (4, 'Joao Pereira', 'joao.pereira', 'hash_demo_004', 1, 1, 4, 'APROVADO', 'Apoio juridico voluntario.');
INSERT INTO VOLUNTARIO (ID, NOME, USUARIO, SENHA, ACESSO_SIGILO, DISPONIVEL, ID_CONTA, STATUS_APROVACAO, MOTIVO_VOLUNTARIADO)
VALUES (5, 'Marina Costa', 'marina.costa', 'hash_demo_005', 0, 1, 5, 'APROVADO', 'Ajudar no acompanhamento escolar.');
INSERT INTO VOLUNTARIO (ID, NOME, USUARIO, SENHA, ACESSO_SIGILO, DISPONIVEL, ID_CONTA, STATUS_APROVACAO, MOTIVO_VOLUNTARIADO)
VALUES (6, 'Rafael Dias', 'rafael.dias', 'hash_demo_006', 0, 1, 6, 'APROVADO', 'Apoio em orientacao de saude.');
INSERT INTO VOLUNTARIO (ID, NOME, USUARIO, SENHA, ACESSO_SIGILO, DISPONIVEL, ID_CONTA, STATUS_APROVACAO, MOTIVO_VOLUNTARIADO)
VALUES (7, 'Laura Mendes', 'laura.mendes', 'hash_demo_007', 0, 0, 7, 'PENDENTE', 'Desejo contribuir com a rede de cuidado.');

-- 14 pessoas atendidas: 7 criancas/adolescentes e 7 mulheres Apolonia.
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (1, 'CA-SOL-001', DATE '2026-05-03', '11990000001', 'ca.sol@example.com', 'CRIANCA_ADOLESCENTE', 8);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (2, 'CA-LUA-002', DATE '2026-05-03', '11990000002', 'ca.lua@example.com', 'CRIANCA_ADOLESCENTE', 9);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (3, 'CA-RIO-003', DATE '2026-05-04', '11990000003', 'ca.rio@example.com', 'CRIANCA_ADOLESCENTE', 10);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (4, 'CA-FLOR-004', DATE '2026-05-04', '11990000004', 'ca.flor@example.com', 'CRIANCA_ADOLESCENTE', 11);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (5, 'CA-MAR-005', DATE '2026-05-05', '11990000005', 'ca.mar@example.com', 'CRIANCA_ADOLESCENTE', 12);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (6, 'CA-VIDA-006', DATE '2026-05-05', '11990000006', 'ca.vida@example.com', 'CRIANCA_ADOLESCENTE', 13);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (7, 'CA-AURORA-007', DATE '2026-05-06', '11990000007', 'ca.aurora@example.com', 'CRIANCA_ADOLESCENTE', 14);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (8, 'AP-ROSA-008', DATE '2026-05-06', '11990000008', 'ap.rosa@example.com', 'MULHER_APOLONIA', NULL);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (9, 'AP-LIRIO-009', DATE '2026-05-07', '11990000009', 'ap.lirio@example.com', 'MULHER_APOLONIA', NULL);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (10, 'AP-VIOLETA-010', DATE '2026-05-07', '11990000010', 'ap.violeta@example.com', 'MULHER_APOLONIA', NULL);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (11, 'AP-JASMIM-011', DATE '2026-05-08', '11990000011', 'ap.jasmim@example.com', 'MULHER_APOLONIA', NULL);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (12, 'AP-IRIS-012', DATE '2026-05-08', '11990000012', 'ap.iris@example.com', 'MULHER_APOLONIA', NULL);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (13, 'AP-DALIA-013', DATE '2026-05-09', '11990000013', 'ap.dalia@example.com', 'MULHER_APOLONIA', NULL);
INSERT INTO PESSOA_ATENDIDA (ID, NOME_CODIFICADO, DATA_CADASTRO, TELEFONE, EMAIL, TIPO, ID_CONTA)
VALUES (14, 'AP-LUZ-014', DATE '2026-05-09', '11990000014', 'ap.luz@example.com', 'MULHER_APOLONIA', NULL);

-- 7 linhas em CRIANCA_ADOLESCENTE.
INSERT INTO CRIANCA_ADOLESCENTE (PESSOA_ID, IDADE, NOME_RESPONSAVEL, ESCOLA, GRAVIDADE_BUCAL) VALUES (1, 8, 'Responsavel Sol', 'Escola Parceira Norte', 5);
INSERT INTO CRIANCA_ADOLESCENTE (PESSOA_ID, IDADE, NOME_RESPONSAVEL, ESCOLA, GRAVIDADE_BUCAL) VALUES (2, 12, 'Responsavel Lua', 'Escola Parceira Sul', 4);
INSERT INTO CRIANCA_ADOLESCENTE (PESSOA_ID, IDADE, NOME_RESPONSAVEL, ESCOLA, GRAVIDADE_BUCAL) VALUES (3, 9, 'Responsavel Rio', 'Escola Esperanca', 3);
INSERT INTO CRIANCA_ADOLESCENTE (PESSOA_ID, IDADE, NOME_RESPONSAVEL, ESCOLA, GRAVIDADE_BUCAL) VALUES (4, 15, 'Responsavel Flor', 'Escola Jardim', 2);
INSERT INTO CRIANCA_ADOLESCENTE (PESSOA_ID, IDADE, NOME_RESPONSAVEL, ESCOLA, GRAVIDADE_BUCAL) VALUES (5, 11, 'Responsavel Mar', 'Escola Caminho', 1);
INSERT INTO CRIANCA_ADOLESCENTE (PESSOA_ID, IDADE, NOME_RESPONSAVEL, ESCOLA, GRAVIDADE_BUCAL) VALUES (6, 7, 'Responsavel Vida', 'Escola Horizonte', 4);
INSERT INTO CRIANCA_ADOLESCENTE (PESSOA_ID, IDADE, NOME_RESPONSAVEL, ESCOLA, GRAVIDADE_BUCAL) VALUES (7, 14, 'Responsavel Aurora', 'Escola Centro', 5);

-- 7 linhas em MULHER_APOLONIA.
INSERT INTO MULHER_APOLONIA (PESSOA_ID, CODINOME, NIVEL_RISCO, TEM_BOLETIM_OCORRENCIA, NECESSITA_SIGILO_ABSOLUTO) VALUES (8, 'Rosa', 5, 1, 1);
INSERT INTO MULHER_APOLONIA (PESSOA_ID, CODINOME, NIVEL_RISCO, TEM_BOLETIM_OCORRENCIA, NECESSITA_SIGILO_ABSOLUTO) VALUES (9, 'Lirio', 4, 1, 1);
INSERT INTO MULHER_APOLONIA (PESSOA_ID, CODINOME, NIVEL_RISCO, TEM_BOLETIM_OCORRENCIA, NECESSITA_SIGILO_ABSOLUTO) VALUES (10, 'Violeta', 3, 0, 1);
INSERT INTO MULHER_APOLONIA (PESSOA_ID, CODINOME, NIVEL_RISCO, TEM_BOLETIM_OCORRENCIA, NECESSITA_SIGILO_ABSOLUTO) VALUES (11, 'Jasmim', 2, 0, 1);
INSERT INTO MULHER_APOLONIA (PESSOA_ID, CODINOME, NIVEL_RISCO, TEM_BOLETIM_OCORRENCIA, NECESSITA_SIGILO_ABSOLUTO) VALUES (12, 'Iris', 1, 0, 0);
INSERT INTO MULHER_APOLONIA (PESSOA_ID, CODINOME, NIVEL_RISCO, TEM_BOLETIM_OCORRENCIA, NECESSITA_SIGILO_ABSOLUTO) VALUES (13, 'Dalia', 4, 1, 1);
INSERT INTO MULHER_APOLONIA (PESSOA_ID, CODINOME, NIVEL_RISCO, TEM_BOLETIM_OCORRENCIA, NECESSITA_SIGILO_ABSOLUTO) VALUES (14, 'Luz', 5, 1, 1);

-- 7 vinculos entre voluntarios e especialidades.
INSERT INTO VOLUNTARIO_ESPECIALIDADE (VOLUNTARIO_ID, ESPECIALIDADE_ID) VALUES (1, 1);
INSERT INTO VOLUNTARIO_ESPECIALIDADE (VOLUNTARIO_ID, ESPECIALIDADE_ID) VALUES (2, 3);
INSERT INTO VOLUNTARIO_ESPECIALIDADE (VOLUNTARIO_ID, ESPECIALIDADE_ID) VALUES (3, 2);
INSERT INTO VOLUNTARIO_ESPECIALIDADE (VOLUNTARIO_ID, ESPECIALIDADE_ID) VALUES (4, 4);
INSERT INTO VOLUNTARIO_ESPECIALIDADE (VOLUNTARIO_ID, ESPECIALIDADE_ID) VALUES (5, 6);
INSERT INTO VOLUNTARIO_ESPECIALIDADE (VOLUNTARIO_ID, ESPECIALIDADE_ID) VALUES (6, 7);
INSERT INTO VOLUNTARIO_ESPECIALIDADE (VOLUNTARIO_ID, ESPECIALIDADE_ID) VALUES (7, 5);

-- 7 atendimentos.
INSERT INTO ATENDIMENTO (ID, PESSOA_ATENDIDA_ID, VOLUNTARIO_ID, CANAL_COMUNICACAO_ID, PRIORIDADE, STATUS, DATA_ABERTURA, DATA_ENCERRAMENTO, DESCRICAO)
VALUES (1, 1, 1, 1, 1, 'EM_ATENDIMENTO', DATE '2026-05-10', NULL, 'Crianca com dor intensa encaminhada pela escola.');
INSERT INTO ATENDIMENTO (ID, PESSOA_ATENDIDA_ID, VOLUNTARIO_ID, CANAL_COMUNICACAO_ID, PRIORIDADE, STATUS, DATA_ABERTURA, DATA_ENCERRAMENTO, DESCRICAO)
VALUES (2, 2, 2, 6, 2, 'EM_ATENDIMENTO', DATE '2026-05-11', NULL, 'Solicitacao de triagem social e odontologica.');
INSERT INTO ATENDIMENTO (ID, PESSOA_ATENDIDA_ID, VOLUNTARIO_ID, CANAL_COMUNICACAO_ID, PRIORIDADE, STATUS, DATA_ABERTURA, DATA_ENCERRAMENTO, DESCRICAO)
VALUES (3, 8, 3, 3, 1, 'ABERTO', DATE '2026-05-12', NULL, 'Caso Apolonia com sigilo absoluto e risco alto.');
INSERT INTO ATENDIMENTO (ID, PESSOA_ATENDIDA_ID, VOLUNTARIO_ID, CANAL_COMUNICACAO_ID, PRIORIDADE, STATUS, DATA_ABERTURA, DATA_ENCERRAMENTO, DESCRICAO)
VALUES (4, 9, 4, 2, 2, 'EM_ATENDIMENTO', DATE '2026-05-13', NULL, 'Orientacao juridica inicial solicitada por telefone.');
INSERT INTO ATENDIMENTO (ID, PESSOA_ATENDIDA_ID, VOLUNTARIO_ID, CANAL_COMUNICACAO_ID, PRIORIDADE, STATUS, DATA_ABERTURA, DATA_ENCERRAMENTO, DESCRICAO)
VALUES (5, 3, 5, 5, 3, 'ABERTO', DATE '2026-05-14', NULL, 'Formulario web para avaliacao de saude bucal.');
INSERT INTO ATENDIMENTO (ID, PESSOA_ATENDIDA_ID, VOLUNTARIO_ID, CANAL_COMUNICACAO_ID, PRIORIDADE, STATUS, DATA_ABERTURA, DATA_ENCERRAMENTO, DESCRICAO)
VALUES (6, 10, 6, 7, 3, 'ENCERRADO', DATE '2026-05-08', DATE '2026-05-15', 'Encaminhamento por ONG parceira encerrado.');
INSERT INTO ATENDIMENTO (ID, PESSOA_ATENDIDA_ID, VOLUNTARIO_ID, CANAL_COMUNICACAO_ID, PRIORIDADE, STATUS, DATA_ABERTURA, DATA_ENCERRAMENTO, DESCRICAO)
VALUES (7, 7, NULL, 4, 1, 'ABERTO', DATE '2026-05-16', NULL, 'Atendimento presencial aguardando voluntario.');

-- 7 mensagens.
INSERT INTO MENSAGEM (ID, ATENDIMENTO_ID, CONTEUDO, DATA_HORA, ENVIADO_POR) VALUES (1, 1, 'A crianca esta com dor desde ontem.', TIMESTAMP '2026-05-10 09:00:00', 'BENEFICIARIO');
INSERT INTO MENSAGEM (ID, ATENDIMENTO_ID, CONTEUDO, DATA_HORA, ENVIADO_POR) VALUES (2, 1, 'Vamos priorizar a avaliacao odontologica.', TIMESTAMP '2026-05-10 09:10:00', 'VOLUNTARIO');
INSERT INTO MENSAGEM (ID, ATENDIMENTO_ID, CONTEUDO, DATA_HORA, ENVIADO_POR) VALUES (3, 2, 'A escola indicou acompanhamento social.', TIMESTAMP '2026-05-11 10:00:00', 'BENEFICIARIO');
INSERT INTO MENSAGEM (ID, ATENDIMENTO_ID, CONTEUDO, DATA_HORA, ENVIADO_POR) VALUES (4, 3, 'Preciso falar com alguem com sigilo.', TIMESTAMP '2026-05-12 11:00:00', 'BENEFICIARIO');
INSERT INTO MENSAGEM (ID, ATENDIMENTO_ID, CONTEUDO, DATA_HORA, ENVIADO_POR) VALUES (5, 4, 'Vou orientar os proximos passos com cuidado.', TIMESTAMP '2026-05-13 12:00:00', 'VOLUNTARIO');
INSERT INTO MENSAGEM (ID, ATENDIMENTO_ID, CONTEUDO, DATA_HORA, ENVIADO_POR) VALUES (6, 6, 'Atendimento encerrado com encaminhamento final.', TIMESTAMP '2026-05-15 16:30:00', 'ADMIN');
INSERT INTO MENSAGEM (ID, ATENDIMENTO_ID, CONTEUDO, DATA_HORA, ENVIADO_POR) VALUES (7, 7, 'Cheguei para o atendimento presencial.', TIMESTAMP '2026-05-16 14:00:00', 'BENEFICIARIO');

-- 7 vinculos mensagem-canal.
INSERT INTO MENSAGEM_CANAL (MENSAGEM_ID, CANAL_ID) VALUES (1, 1);
INSERT INTO MENSAGEM_CANAL (MENSAGEM_ID, CANAL_ID) VALUES (2, 1);
INSERT INTO MENSAGEM_CANAL (MENSAGEM_ID, CANAL_ID) VALUES (3, 6);
INSERT INTO MENSAGEM_CANAL (MENSAGEM_ID, CANAL_ID) VALUES (4, 3);
INSERT INTO MENSAGEM_CANAL (MENSAGEM_ID, CANAL_ID) VALUES (5, 2);
INSERT INTO MENSAGEM_CANAL (MENSAGEM_ID, CANAL_ID) VALUES (6, 7);
INSERT INTO MENSAGEM_CANAL (MENSAGEM_ID, CANAL_ID) VALUES (7, 4);

-- 7 registros de historico.
INSERT INTO HISTORICO_STATUS (ID, ATENDIMENTO_ID, STATUS_ANTERIOR, STATUS_NOVO, ALTERADO_POR_ID, DATA_HORA) VALUES (1, 1, 'ABERTO', 'EM_ATENDIMENTO', 1, TIMESTAMP '2026-05-10 09:05:00');
INSERT INTO HISTORICO_STATUS (ID, ATENDIMENTO_ID, STATUS_ANTERIOR, STATUS_NOVO, ALTERADO_POR_ID, DATA_HORA) VALUES (2, 2, 'ABERTO', 'EM_ATENDIMENTO', 2, TIMESTAMP '2026-05-11 10:15:00');
INSERT INTO HISTORICO_STATUS (ID, ATENDIMENTO_ID, STATUS_ANTERIOR, STATUS_NOVO, ALTERADO_POR_ID, DATA_HORA) VALUES (3, 3, NULL, 'ABERTO', 3, TIMESTAMP '2026-05-12 11:05:00');
INSERT INTO HISTORICO_STATUS (ID, ATENDIMENTO_ID, STATUS_ANTERIOR, STATUS_NOVO, ALTERADO_POR_ID, DATA_HORA) VALUES (4, 4, 'ABERTO', 'EM_ATENDIMENTO', 4, TIMESTAMP '2026-05-13 12:05:00');
INSERT INTO HISTORICO_STATUS (ID, ATENDIMENTO_ID, STATUS_ANTERIOR, STATUS_NOVO, ALTERADO_POR_ID, DATA_HORA) VALUES (5, 5, NULL, 'ABERTO', 5, TIMESTAMP '2026-05-14 13:00:00');
INSERT INTO HISTORICO_STATUS (ID, ATENDIMENTO_ID, STATUS_ANTERIOR, STATUS_NOVO, ALTERADO_POR_ID, DATA_HORA) VALUES (6, 6, 'EM_ATENDIMENTO', 'ENCERRADO', 6, TIMESTAMP '2026-05-15 16:25:00');
INSERT INTO HISTORICO_STATUS (ID, ATENDIMENTO_ID, STATUS_ANTERIOR, STATUS_NOVO, ALTERADO_POR_ID, DATA_HORA) VALUES (7, 7, NULL, 'ABERTO', NULL, TIMESTAMP '2026-05-16 14:05:00');

COMMIT;

-- Validacao de quantidade minima por tabela.
SELECT 'T_CONTA_USUARIO' AS TABELA, COUNT(*) AS TOTAL FROM T_CONTA_USUARIO
UNION ALL SELECT 'CANAL_COMUNICACAO', COUNT(*) FROM CANAL_COMUNICACAO
UNION ALL SELECT 'ESPECIALIDADE', COUNT(*) FROM ESPECIALIDADE
UNION ALL SELECT 'VOLUNTARIO', COUNT(*) FROM VOLUNTARIO
UNION ALL SELECT 'PESSOA_ATENDIDA', COUNT(*) FROM PESSOA_ATENDIDA
UNION ALL SELECT 'CRIANCA_ADOLESCENTE', COUNT(*) FROM CRIANCA_ADOLESCENTE
UNION ALL SELECT 'MULHER_APOLONIA', COUNT(*) FROM MULHER_APOLONIA
UNION ALL SELECT 'VOLUNTARIO_ESPECIALIDADE', COUNT(*) FROM VOLUNTARIO_ESPECIALIDADE
UNION ALL SELECT 'ATENDIMENTO', COUNT(*) FROM ATENDIMENTO
UNION ALL SELECT 'MENSAGEM', COUNT(*) FROM MENSAGEM
UNION ALL SELECT 'MENSAGEM_CANAL', COUNT(*) FROM MENSAGEM_CANAL
UNION ALL SELECT 'HISTORICO_STATUS', COUNT(*) FROM HISTORICO_STATUS;
