quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}

quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=${DB_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl}
quarkus.datasource.username=${DB_USERNAME:SEU_RM}
quarkus.datasource.password=${DB_PASSWORD:SUA_SENHA}

quarkus.datasource.jdbc.max-size=20
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.acquisition-timeout=10S

quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS:https://tdb-responde-full.vercel.app,http://localhost:5173}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# URL da API Python de Inteligencia Artificial
ia.api.url=${IA_API_URL:http://127.0.0.1:5000}
classificador-api/mp-rest/url=${IA_API_URL:http://127.0.0.1:5000}
classificador-api/mp-rest/connectTimeout=500
classificador-api/mp-rest/readTimeout=500
