quarkus.http.port=8080

quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=${DB_URL:jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl}
quarkus.datasource.username=${DB_USERNAME:rm567598}
quarkus.datasource.password=${DB_PASSWORD:270906}
quarkus.datasource.jdbc.max-size=8
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.acquisition-timeout=10S
quarkus.datasource.jdbc.background-validation-interval=30S
quarkus.datasource.jdbc.validation-query-sql=SELECT 1 FROM DUAL

quarkus.jackson.serialization-inclusion=non-null


admin.seed.enabled=${ADMIN_SEED_ENABLED:true}
admin.seed.email=${ADMIN_SEED_EMAIL:admin@tdbresponde.com}
admin.seed.password=${ADMIN_SEED_PASSWORD:123456}
admin.seed.name=${ADMIN_SEED_NAME:Administrador}

quarkus.http.cors=true
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,content-type
